import { opaque } from "./auth";
import { json, problem, readJson } from "./http";
import type { Env, Principal } from "./types";
import { compressionJoins, compressionSelect, saveCompressionStatements } from "./compression";

const TYPES=new Set(["text/markdown","application/json","text/plain"]), MAX=256_000;
const bad=(message:string)=>problem(400,"invalid_request",message);
function validContent(content:unknown,type:unknown){if(typeof content!=="string"||new TextEncoder().encode(content).byteLength>MAX)return "content must be a string no larger than 256,000 bytes";if(typeof type!=="string"||!TYPES.has(type))return "unsupported contentType";if(type==="application/json")try{JSON.parse(content)}catch{return "content must be valid JSON"}return null}
function deadline(now:Date){return new Date(now.getTime()+72*60*60*1000).toISOString()}
function activity(env:Env,projectId:string,type:string,actor:string,details:unknown,at:string){return env.DB.prepare(`INSERT INTO project_events(id,project_id,event_type,actor_participant_id,details_json,created_at) SELECT ?,?,?,?,?,? WHERE changes()=1`).bind(opaque("pev"),projectId,type,actor,JSON.stringify(details),at)}

export async function createProjectDocument(request:Request,env:Env,p:Principal,projectId:string,sourceId?:string){let v:Record<string,unknown>;try{v=await readJson(request)}catch(e){return bad((e as Error).message)}
  let content=v.content,contentType=v.contentType,title=v.title,logicalPath=v.logicalPath;
  let sourceOwner:string|null=null,sourceVersion:string|null=null;
  if(sourceId){const source=await env.DB.prepare(`SELECT title,logical_path,v.id version_id,v.content,v.content_type,d.owner_id FROM documents d JOIN document_versions v ON v.id=d.current_version_id WHERE d.id=? AND d.owner_type='participant' AND d.owner_id=? AND d.deleted_at IS NULL`).bind(sourceId,p.participantId).first<{title:string;logical_path:string;version_id:string;content:string;content_type:string;owner_id:string}>();if(!source)return problem(404,"not_found","Source document not found");if(v.confirmProjectOwnership!==true)return bad("confirmProjectOwnership must be true");title=typeof title==="string"?title:source.title;logicalPath=typeof logicalPath==="string"?logicalPath:source.logical_path;content=source.content;contentType=source.content_type;sourceOwner=source.owner_id;sourceVersion=source.version_id}
  const id=opaque("doc");if(logicalPath===undefined)logicalPath=`documents/${id}`;
  if(typeof title!=="string"||!title.trim()||title.length>200||typeof logicalPath!=="string"||!logicalPath.trim()||logicalPath.length>500)return bad("title and logicalPath are required");const contentProblem=validContent(content,contentType);if(contentProblem)return bad(contentProblem);
  const version=opaque("ver"),now=new Date(),at=now.toISOString(),until=deadline(now),eventType=sourceId?"native_document_copied":"native_document_created";
  try{const result=await env.DB.batch([
    env.DB.prepare(`INSERT INTO documents(id,owner_type,owner_id,kind,title,logical_path,current_version_id,visibility,created_at,created_by_participant_id,creator_deletion_until,source_document_id,source_owner_participant_id) SELECT ?,'project',?,'document',?,?,?,'private',?,?,?,?,? WHERE EXISTS(SELECT 1 FROM projects x JOIN project_members m ON m.project_id=x.id JOIN participants a ON a.id=m.participant_id WHERE x.id=? AND x.lifecycle_state='active' AND m.participant_id=? AND a.account_state!='deleted' AND (a.deletion_due_at IS NULL OR a.deletion_due_at>?)) AND (? IS NULL OR EXISTS(SELECT 1 FROM documents source WHERE source.id=? AND source.owner_type='participant' AND source.owner_id=? AND source.deleted_at IS NULL AND source.current_version_id=?))`).bind(id,projectId,title.trim(),logicalPath.trim(),version,at,p.participantId,until,sourceId??null,sourceOwner,projectId,p.participantId,at,sourceId??null,sourceId??null,p.participantId,sourceVersion),
    env.DB.prepare(`INSERT INTO document_versions(id,document_id,version_number,content,content_type,actor_type,actor_id,created_at) SELECT ?,?,1,?,?,'human',?,? WHERE EXISTS(SELECT 1 FROM documents WHERE id=? AND owner_type='project')`).bind(version,id,content,contentType,p.participantId,at,id),
    activity(env,projectId,eventType,p.participantId,{documentId:id,sourceDocumentId:sourceId??undefined},at)
  ]);if(!result[0].meta.changes)return problem(409,"project_mutation_conflict","Project state, membership, or account authority changed before creation committed")}catch(e){if(String(e).includes("UNIQUE"))return problem(409,"path_conflict","That project path is already in use");throw e}
  return json({document:{id,owner:{type:"project",id:projectId},createdBy:p.participantId,creatorDeletionUntil:until,sourceDocumentId:sourceId??null}},201)
}

export async function uploadProjectDocument(request:Request,env:Env,p:Principal,projectId:string){let form:FormData;try{form=await request.formData()}catch{return problem(400,"invalid_upload","Expected multipart form data")}const file=form.get("file");if(!(file instanceof File))return problem(400,"invalid_upload","A file is required");if(file.size>MAX)return problem(413,"file_too_large","Files may not exceed 256,000 bytes");const extension=file.name.toLowerCase().match(/\.(md|txt|json)$/)?.[1],contentType=extension==="md"?"text/markdown":extension==="txt"?"text/plain":extension==="json"?"application/json":null;if(!contentType)return problem(415,"unsupported_file","Only .md, .txt, and .json files are supported");return createProjectDocument(new Request(request.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:String(form.get("title")||file.name.replace(/\.[^.]+$/,"")),content:await file.text(),contentType})}),env,p,projectId)}

export async function readProjectDocument(env:Env,p:Principal,id:string){const now=new Date().toISOString(),row=await env.DB.prepare(`SELECT d.id,d.owner_id project_id,d.title,d.logical_path,d.compression,d.created_at,d.created_by_participant_id,d.creator_deletion_until,d.source_document_id ${compressionSelect("d")},v.version_number,v.content,v.content_type,v.created_at updated_at,COALESCE(u.display_name,q.provenance_identifier||' (former user)') creator_display_name,(x.lifecycle_state='active') can_edit,(x.lifecycle_state='active' AND m.role IN ('owner','admin') OR d.created_by_participant_id=? AND d.creator_deletion_until>?) can_delete FROM documents d JOIN projects x ON x.id=d.owner_id JOIN project_members m ON m.project_id=x.id AND m.participant_id=? JOIN document_versions v ON v.id=d.current_version_id ${compressionJoins("d")} LEFT JOIN participants q ON q.id=d.created_by_participant_id LEFT JOIN users u ON u.id=q.user_id WHERE d.id=? AND d.owner_type='project' AND d.deleted_at IS NULL AND x.read_audience='members_and_agents'`).bind(p.participantId,now,p.participantId,id).first();return row?json({document:row}):problem(404,"not_found","Document not found")}

export async function updateProjectDocument(request:Request,env:Env,p:Principal,id:string){let v;try{v=await readJson(request)}catch(e){return bad((e as Error).message)}const error=validContent(v.content,v.contentType);if(error)return bad(error);const now=new Date().toISOString(),version=opaque("ver"),marker=opaque("ver");const result=await env.DB.batch([
  env.DB.prepare(`INSERT INTO document_versions(id,document_id,version_number,content,content_type,actor_type,actor_id,created_at) SELECT ?,d.id,COALESCE((SELECT MAX(version_number)+1 FROM document_versions WHERE document_id=d.id),1),?,?,'human',?,? FROM documents d JOIN projects x ON x.id=d.owner_id JOIN project_members m ON m.project_id=x.id JOIN participants a ON a.id=m.participant_id WHERE d.id=? AND d.owner_type='project' AND d.deleted_at IS NULL AND x.lifecycle_state='active' AND m.participant_id=? AND a.account_state!='deleted' AND (a.deletion_due_at IS NULL OR a.deletion_due_at>?)`).bind(version,v.content,v.contentType,p.participantId,now,id,p.participantId,now),
  env.DB.prepare(`UPDATE documents SET current_version_id=? WHERE id=? AND EXISTS(SELECT 1 FROM document_versions WHERE id=?)`).bind(version,id,version),
  env.DB.prepare(`INSERT INTO project_events(id,project_id,event_type,actor_participant_id,details_json,created_at) SELECT ?,owner_id,'native_document_edited',?,?,? FROM documents WHERE id=? AND current_version_id=?`).bind(marker,p.participantId,JSON.stringify({documentId:id}),now,id,version)
]);return result[0].meta.changes?json({document:{id,versionId:version}}):problem(409,"project_mutation_conflict","Project state, membership, or account authority changed before editing committed")}

export async function updateProjectDocumentMetadata(request:Request,env:Env,p:Principal,id:string){
  let v;try{v=await readJson(request)}catch(e){return bad((e as Error).message)}
  if(typeof v.title!=="string"||!v.title.trim()||v.title.length>200||typeof v.logicalPath!=="string"||!v.logicalPath.trim()||v.logicalPath.length>500||!(v.compression===undefined||v.compression===null||typeof v.compression==="string"&&v.compression.length<=2000))return bad("title, logicalPath, or compression is invalid");
  const before=await env.DB.prepare(`SELECT title,logical_path,compression,owner_id,current_version_id FROM documents WHERE id=? AND owner_type='project'`).bind(id).first<{title:string;logical_path:string;compression:string|null;owner_id:string;current_version_id:string}>();if(!before)return problem(404,"not_found","Document not found");
  const compression=v.compression===undefined?before.compression:v.compression===""?null:v.compression,compressionChanged=compression!==before.compression,sourceVersionId=v.sourceVersionId===undefined?before.current_version_id:v.sourceVersionId;
  if(compressionChanged&&typeof sourceVersionId!=="string")return bad("sourceVersionId is required when saving compression");
  const now=new Date().toISOString(),changes=JSON.stringify({title:{previous:before.title,new:v.title.trim()},logicalPath:{previous:before.logical_path,new:v.logicalPath.trim()},...(compressionChanged?{compressionRevision:{previous:null,new:"created"}}:{})});
  const authorization="d.owner_type='project' AND EXISTS(SELECT 1 FROM projects x JOIN project_members m ON m.project_id=x.id JOIN participants a ON a.id=m.participant_id WHERE x.id=d.owner_id AND x.lifecycle_state='active' AND m.participant_id=? AND a.account_state!='deleted' AND (a.deletion_due_at IS NULL OR a.deletion_due_at>?))";
  try{
    const save=compressionChanged?saveCompressionStatements(env,{documentId:id,text:compression as string|null,sourceVersionId,actorId:p.participantId,authorizeSql:authorization,authorizeBindings:[p.participantId,now]}):null;
    const results=await env.DB.batch(compressionChanged?[
      ...save!.statements,
      env.DB.prepare(`UPDATE documents AS d SET title=?,logical_path=? WHERE id=? AND current_version_id=? AND ((? IS NULL AND selected_compression_revision_id IS NULL) OR selected_compression_revision_id=?) AND (${authorization})`).bind(v.title.trim(),v.logicalPath.trim(),id,sourceVersionId,save!.id,save!.id,p.participantId,now),
      env.DB.prepare(`INSERT INTO document_events(id,document_id,event_type,actor_type,actor_id,changes_json,created_at) SELECT ?,?,'metadata_changed','human',?,?,? WHERE EXISTS(SELECT 1 FROM documents d WHERE d.id=? AND d.current_version_id=? AND ((? IS NULL AND d.selected_compression_revision_id IS NULL) OR d.selected_compression_revision_id=?) AND (${authorization}))`).bind(opaque("dev"),id,p.participantId,changes,now,id,sourceVersionId,save!.id,save!.id,p.participantId,now),
      env.DB.prepare(`INSERT INTO project_events(id,project_id,event_type,actor_participant_id,details_json,created_at) SELECT ?,?,'native_document_edited',?,?,? WHERE EXISTS(SELECT 1 FROM documents WHERE id=? AND current_version_id=? AND ((? IS NULL AND selected_compression_revision_id IS NULL) OR selected_compression_revision_id=?))`).bind(opaque("pev"),before.owner_id,p.participantId,JSON.stringify({documentId:id,metadata:true}),now,id,sourceVersionId,save!.id,save!.id),
    ]:[
      env.DB.prepare(`UPDATE documents AS d SET title=?,logical_path=? WHERE id=? AND (${authorization})`).bind(v.title.trim(),v.logicalPath.trim(),id,p.participantId,now),
      env.DB.prepare(`INSERT INTO document_events(id,document_id,event_type,actor_type,actor_id,changes_json,created_at) SELECT ?,?,'metadata_changed','human',?,?,? WHERE changes()=1`).bind(opaque("dev"),id,p.participantId,changes,now),
      env.DB.prepare(`INSERT INTO project_events(id,project_id,event_type,actor_participant_id,details_json,created_at) SELECT ?,?,'native_document_edited',?,?,? WHERE changes()=1`).bind(opaque("pev"),before.owner_id,p.participantId,JSON.stringify({documentId:id,metadata:true}),now),
    ]);
    if(compressionChanged&&!results[0]?.meta.changes)return problem(409,"document_version_conflict","The document changed since this compression was prepared");
    if(!compressionChanged&&!results[0]?.meta.changes)return problem(409,"project_mutation_conflict","Project state, membership, or account authority changed before metadata editing committed");
    return json({document:{id}})
  }catch(e){if(String(e).includes("UNIQUE"))return problem(409,"path_conflict","That project path is already in use");throw e}
}

export async function deleteProjectDocument(env:Env,p:Principal,id:string,authorizationTimeOverride?:string){const eventAt=new Date().toISOString(),eventId=opaque("pev");const exists=await env.DB.prepare(`SELECT 1 ok FROM documents WHERE id=? AND owner_type='project'`).bind(id).first();if(!exists)return problem(404,"not_found","Document not found");const results=await env.DB.batch([
  env.DB.prepare(`INSERT INTO project_events(id,project_id,event_type,actor_participant_id,details_json,created_at) SELECT ?,owner_id,'native_document_deleted',?,json_object('documentId',id,'title',title),? FROM documents WHERE id=? AND owner_type='project' AND (EXISTS(SELECT 1 FROM projects x JOIN project_members m ON m.project_id=x.id WHERE x.id=documents.owner_id AND x.lifecycle_state='active' AND m.participant_id=? AND m.role IN ('owner','admin')) OR (created_by_participant_id=? AND creator_deletion_until>COALESCE(?,strftime('%Y-%m-%dT%H:%M:%fZ','now')) AND EXISTS(SELECT 1 FROM participants a WHERE a.id=? AND a.account_state!='deleted' AND (a.deletion_due_at IS NULL OR a.deletion_due_at>COALESCE(?,strftime('%Y-%m-%dT%H:%M:%fZ','now'))))))`).bind(eventId,p.participantId,eventAt,id,p.participantId,p.participantId,authorizationTimeOverride??null,p.participantId,authorizationTimeOverride??null),
  env.DB.prepare(`DELETE FROM documents WHERE id=? AND owner_type='project' AND EXISTS(SELECT 1 FROM project_events WHERE id=? AND project_id=documents.owner_id)`).bind(id,eventId)
]);if(!results[1].meta.changes)return problem(403,"deletion_not_authorized","No live creator entitlement or active project administrator authority");return new Response(null,{status:204})}

export async function listCreatorEntitlements(env:Env,p:Principal){const now=new Date().toISOString(),rows=await env.DB.prepare(`SELECT id,title,owner_id project_id,creator_deletion_until FROM documents WHERE owner_type='project' AND created_by_participant_id=? AND deleted_at IS NULL AND creator_deletion_until>? ORDER BY creator_deletion_until`).bind(p.participantId,now).all();return json({entitlements:rows.results})}

export async function projectDocumentHistory(env:Env,p:Principal,id:string){const access=await env.DB.prepare(`SELECT 1 ok FROM documents d JOIN projects x ON x.id=d.owner_id JOIN project_members m ON m.project_id=x.id WHERE d.id=? AND d.owner_type='project' AND m.participant_id=? AND x.read_audience='members_and_agents'`).bind(id,p.participantId).first();if(!access)return problem(404,"not_found","Document not found");const rows=await env.DB.prepare(`SELECT v.id,v.version_number,v.content,v.content_type,v.actor_type,v.actor_id,v.created_at,COALESCE(u.display_name,q.provenance_identifier||' (former user)') actor_display_name FROM document_versions v LEFT JOIN participants q ON q.id=v.actor_id LEFT JOIN users u ON u.id=q.user_id WHERE v.document_id=? ORDER BY v.version_number DESC`).bind(id).all<Record<string,unknown>>();const events=await env.DB.prepare(`SELECT e.id,e.event_type,e.actor_type,e.actor_id,e.changes_json,e.created_at,COALESCE(u.display_name,q.provenance_identifier||' (former user)') actor_display_name FROM document_events e LEFT JOIN participants q ON q.id=e.actor_id LEFT JOIN users u ON u.id=q.user_id WHERE e.document_id=? ORDER BY e.created_at DESC,e.id DESC`).bind(id).all<Record<string,unknown>>();const compressions=await env.DB.prepare(`SELECT cr.id,cr.revision_number,cr.text,cr.source_version_id,sv.version_number source_version_number,cr.actor_type,cr.actor_id,cr.created_at,cr.prompt_version,cr.migrated_at,COALESCE(u.display_name,q.provenance_identifier||' (former user)') actor_display_name FROM compression_revisions cr LEFT JOIN document_versions sv ON sv.id=cr.source_version_id AND sv.document_id=cr.document_id LEFT JOIN participants q ON q.id=cr.actor_id LEFT JOIN users u ON u.id=q.user_id WHERE cr.document_id=? ORDER BY cr.revision_number DESC`).bind(id).all<Record<string,unknown>>();const timeline:Array<Record<string,unknown>>=[...rows.results.map(x=>({...x,entry_type:"content_revision"})),...events.results.map(x=>({...x,entry_type:"metadata_event",changes:JSON.parse(String(x.changes_json)),changes_json:undefined})),...compressions.results.map(x=>({...x,entry_type:"compression_revision"}))].sort((a:Record<string,unknown>,b:Record<string,unknown>)=>String(b["created_at"]).localeCompare(String(a["created_at"]))||String(b["id"]).localeCompare(String(a["id"])));return json({versions:rows.results,compressionRevisions:compressions.results,timeline})}
