const style = `<style>body{font:16px system-ui;max-width:760px;margin:3rem auto;padding:0 1rem;color:#172033}a,button{color:#3454d1}textarea,input,select{box-sizing:border-box;width:100%;padding:.65rem;margin:.3rem 0 1rem}textarea{min-height:12rem}article{border:1px solid #ccd3df;padding:1rem;margin:1rem 0;border-radius:8px}</style>`;
export function loginPage(): Response {
  return new Response(`<!doctype html><title>Loom — Sign in</title>${style}<main><h1>Loom</h1><p>Your participant-owned writing space.</p><a href="/auth/discord">Continue with Discord</a></main>`, { headers: { "content-type": "text/html; charset=utf-8" } });
}
export function spacePage(displayName: string, participantId: string): Response {
  return new Response(`<!doctype html><title>My Space — Loom</title>${style}<main><h1>${escapeHtml(displayName)}’s space</h1><p>Your stable participant ID: <code>${participantId}</code></p><form id="new"><label>Title<input name="title" maxlength="120" required></label><label>Kind<select name="kind"><option value="document">Document</option><option value="profile">Profile</option><option value="introduction">Introduction</option></select></label><label>Visibility<select name="visibility"><option value="private">Private</option><option value="public">Public</option></select></label><label>Markdown<textarea name="content" required></textarea></label><button>Create document</button></form><section id="documents"></section></main><script>
const docs=document.querySelector('#documents'); async function load(){const r=await fetch('/api/me/documents');const j=await r.json();docs.replaceChildren(...j.documents.map(d=>{const a=document.createElement('article');a.innerHTML='<h2></h2><p></p><pre></pre>';a.querySelector('h2').textContent=d.title;a.querySelector('p').textContent=d.visibility+' · revision '+d.version_number;a.querySelector('pre').textContent=d.content;return a}));}document.querySelector('#new').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/me/documents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:f.get('title'),kind:f.get('kind'),visibility:f.get('visibility'),content:f.get('content'),contentType:'text/markdown'})});if(r.ok){e.target.reset();load()}else alert((await r.json()).error.message)};load();
</script>`, { headers: { "content-type": "text/html; charset=utf-8", "content-security-policy": "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; frame-ancestors 'none'" } });
}
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }
