import { env } from "cloudflare:workers";
import { SELF } from "cloudflare:test";
import { beforeEach, describe, expect, it } from "vitest";
import { deleteProjectDocument } from "../../src/project-documents";
import { finalizeDueAccounts } from "../../src/accounts";
import { acceptanceCase, actor, agentRequest, agentTokens, AT, coveredCases, expectStatus, ids, NOW, origin, request, resetReferenceWorld } from "./harness";
import { caseName, operationBranches } from "./catalog";

beforeEach(resetReferenceWorld);
const json={"content-type":"application/json"};
const gptAction=(credential:unknown,init:RequestInit={})=>SELF.fetch(origin+"/api/gpt-action/authenticate",{method:"POST",headers:json,body:JSON.stringify({credential}),...init});

describe("deterministic acceptance: GPT Action credential handoff",()=>{
  acceptanceCase(caseName("gpt-action.authenticate","active.allowed-and-equivalent"),async()=>{const canonical=await agentRequest("/api/agent/me","readOnly").then(r=>r.json()),action=await gptAction(agentTokens.readOnly);expectStatus(action,200);expect(action.headers.get("cache-control")).toBe("no-store");expect(await action.json()).toEqual(canonical)});
  acceptanceCase(caseName("gpt-action.authenticate","malformed.denied"),async()=>{expectStatus(await gptAction("not-a-token"),401)});
  acceptanceCase(caseName("gpt-action.authenticate","unknown.denied"),async()=>{expectStatus(await gptAction(`loom_agent_${"0".repeat(36)}`),401)});
  acceptanceCase(caseName("gpt-action.authenticate","revoked.denied"),async()=>{expectStatus(await gptAction(agentTokens.revoked),401)});
  acceptanceCase(caseName("gpt-action.authenticate","archived.allowed"),async()=>{expectStatus(await gptAction(agentTokens.archived),200)});
  acceptanceCase(caseName("gpt-action.authenticate","deletion-scheduled.allowed"),async()=>{await env.DB.prepare("UPDATE projects SET lifecycle_state='archived',deletion_due_at=? WHERE id=?").bind("2099-01-01T00:00:00.000Z",ids.projects.active).run();expectStatus(await gptAction(agentTokens.readOnly),200)});
  acceptanceCase(caseName("gpt-action.authenticate","shell.denied"),async()=>{await env.DB.prepare("UPDATE projects SET lifecycle_state='shell' WHERE id=?").bind(ids.projects.active).run();expectStatus(await gptAction(agentTokens.readOnly),410)});
  acceptanceCase(caseName("gpt-action.authenticate","unsupported-method.denied"),async()=>{expectStatus(await SELF.fetch(origin+"/api/gpt-action/authenticate",{method:"GET",headers:{authorization:`Bearer ${agentTokens.readOnly}`}}),405)});
  acceptanceCase(caseName("gpt-action.authenticate","credential-not-disclosed"),async()=>{const response=await gptAction(agentTokens.readOnly);expect(JSON.stringify(await response.json())).not.toContain(agentTokens.readOnly);expect(JSON.stringify((await env.DB.prepare("SELECT * FROM machine_read_audit").all()).results)).not.toContain(agentTokens.readOnly)});
  acceptanceCase(caseName("gpt-action.authenticate","schema.single-operation"),async()=>{const schema=await SELF.fetch(origin+"/openapi/gpt-action.json").then(r=>r.json<any>());expect(Object.keys(schema.paths)).toEqual(["/api/gpt-action/authenticate"]);expect(Object.keys(schema.paths["/api/gpt-action/authenticate"])).toEqual(["post"]);expect(schema.paths["/api/gpt-action/authenticate"].post.operationId).toBe("authenticateLoomCredential")});
});

describe("deterministic acceptance: native agent entrance and check-in",()=>{
  acceptanceCase(caseName("agent.discovery","llms.public"),async()=>{const response=await SELF.fetch(origin+"/llms.txt"),text=await response.text();expectStatus(response,200);expect(response.headers.get("content-type")).toContain("text/plain");expect(text).toContain("/agent");expect(text).toContain("/.well-known/loom-agent")});
  acceptanceCase(caseName("agent.discovery","well-known.public-non-secret"),async()=>{const response=await SELF.fetch(origin+"/.well-known/loom-agent"),body=await response.json<any>();expectStatus(response,200);expect(body).toMatchObject({service:"Loom",entrance:"/agent",endpoints:{checkin:"/api/agent/check-in"}});expect(JSON.stringify(body)).not.toMatch(/projectId|credentialId|fingerprint|token_hash/)});
  acceptanceCase(caseName("agent.discovery","entrance.public-parseable"),async()=>{const response=await SELF.fetch(origin+"/agent"),html=await response.text(),script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1]??"";expectStatus(response,200);expect(html).toContain('type="password"');expect(()=>new Function(script)).not.toThrow()});
  acceptanceCase(caseName("agent.discovery","human-login.unchanged"),async()=>{const response=await SELF.fetch(origin+"/login");expectStatus(response,200);expect(await response.text()).toContain("Continue with Discord")});
  acceptanceCase(caseName("agent-checkin.write","read-only.denied"),async()=>{expectStatus(await agentRequest("/api/agent/check-in","readOnly",{method:"POST",headers:json,body:JSON.stringify({value:"denied"})}),403);expect((await env.DB.prepare("SELECT count(*) count FROM project_machine_checkins").first<{count:number}>())!.count).toBe(0)});
  acceptanceCase(caseName("agent-checkin.write","enabled.active.allowed"),async()=>{const me=await agentRequest("/api/agent/me","checkin").then(r=>r.json<any>());expect(me.caller.grant.capabilities).toContain("agent_checkin:write");expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:JSON.stringify({value:"reference ready"})}),201);expect(await env.DB.prepare("SELECT credential_id,project_id,value FROM project_machine_checkins").first()).toEqual({credential_id:ids.credentials.checkin,project_id:ids.projects.active,value:"reference ready"})});
  acceptanceCase(caseName("agent-checkin.write","provenance.owner-inspectable"),async()=>{expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:JSON.stringify({value:"inspect this"})}),201);const project=await request(`/api/projects/${ids.projects.active}`,"owner").then(r=>r.json<any>()),event=project.events.find((x:any)=>x.event_type==="agent_checkin");expect(event).toMatchObject({credential_id:ids.credentials.checkin,credential_label:"Reference check-in",checkin_value:"inspect this"});expect(event.created_at).toBeTruthy()});
  acceptanceCase(caseName("agent-checkin.write","malformed.denied"),async()=>{expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:"{"}),400)});
  acceptanceCase(caseName("agent-checkin.write","oversized.denied"),async()=>{expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:JSON.stringify({value:"x".repeat(501)})}),400)});
  acceptanceCase(caseName("agent-checkin.write","revoked.denied"),async()=>{expectStatus(await agentRequest("/api/agent/check-in","revoked",{method:"POST",headers:json,body:JSON.stringify({value:"no"})}),401)});
  acceptanceCase(caseName("agent-checkin.write","archived.denied"),async()=>{expectStatus(await agentRequest("/api/agent/check-in","archived",{method:"POST",headers:json,body:JSON.stringify({value:"no"})}),403)});
  acceptanceCase(caseName("agent-checkin.write","deletion-scheduled.denied"),async()=>{await env.DB.prepare("UPDATE projects SET lifecycle_state='archived',deletion_due_at=? WHERE id=?").bind("2099-01-01T00:00:00.000Z",ids.projects.active).run();expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:JSON.stringify({value:"no"})}),403)});
  acceptanceCase(caseName("agent-checkin.write","shell.denied"),async()=>{await env.DB.prepare("UPDATE projects SET lifecycle_state='shell' WHERE id=?").bind(ids.projects.active).run();expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:JSON.stringify({value:"no"})}),410)});
  acceptanceCase(caseName("agent-checkin.write","stale-lifecycle.denied"),async()=>{const me=await agentRequest("/api/agent/me","checkin").then(r=>r.json<any>());expect(me.caller.grant.capabilities).toContain("agent_checkin:write");await env.DB.prepare("UPDATE projects SET lifecycle_state='archived' WHERE id=?").bind(ids.projects.active).run();expectStatus(await agentRequest("/api/agent/check-in","checkin",{method:"POST",headers:json,body:JSON.stringify({value:"stale"})}),403);expect((await env.DB.prepare("SELECT count(*) count FROM project_machine_checkins").first<{count:number}>())!.count).toBe(0)});
});

describe("deterministic acceptance: project-native documents",()=>{
  for(const role of ["owner","admin","member"] as const)acceptanceCase(caseName("project-native.create",`${role}.active.allowed`),async()=>{const response=await request(`/api/projects/${ids.projects.active}/native-documents`,role,{method:"POST",headers:json,body:JSON.stringify({title:`Made by ${role}`,logicalPath:`${role}.md`,content:"content",contentType:"text/plain"})});expectStatus(response,201);expect(await env.DB.prepare("SELECT owner_type,owner_id,created_by_participant_id FROM documents WHERE title=?").bind(`Made by ${role}`).first()).toEqual({owner_type:"project",owner_id:ids.projects.active,created_by_participant_id:ids.participants[role]})});
  acceptanceCase(caseName("project-native.create","default-path.allowed"),async()=>{const response=await request(`/api/projects/${ids.projects.active}/native-documents`,"member",{method:"POST",headers:json,body:JSON.stringify({title:"Default path",content:"content",contentType:"text/plain"})});expectStatus(response,201);const id=(await response.json<any>()).document.id;expect((await env.DB.prepare("SELECT logical_path FROM documents WHERE id=?").bind(id).first<any>()).logical_path).toBe(`documents/${id}`)});
  acceptanceCase(caseName("project-native.create","direct-upload.allowed"),async()=>{const form=new FormData();form.set("file",new File(["uploaded"],"acceptance.txt",{type:"text/plain"}));const response=await request(`/api/projects/${ids.projects.active}/native-documents/upload`,"member",{method:"POST",body:form});expectStatus(response,201);const id=(await response.json<any>()).document.id;expect(await env.DB.prepare("SELECT owner_type,owner_id,title FROM documents WHERE id=?").bind(id).first()).toEqual({owner_type:"project",owner_id:ids.projects.active,title:"acceptance"})});
  acceptanceCase(caseName("project-native.edit","admin.active.allowed"),async()=>{expectStatus(await request(`/api/project-documents/${ids.documents.nativeLive}`,"admin",{method:"PUT",headers:json,body:JSON.stringify({content:"admin revision",contentType:"text/plain"})}),200);expect((await env.DB.prepare("SELECT count(*) count FROM document_versions WHERE document_id=?").bind(ids.documents.nativeLive).first<{count:number}>())!.count).toBe(2)});
  acceptanceCase(caseName("project-native.delete","creator.voluntary-leave.before.allowed"),async()=>{expectStatus(await request(`/api/projects/${ids.projects.active}/members/${ids.participants.member}`,"member",{method:"DELETE",headers:json,body:JSON.stringify({withdrawContributions:false})}),204);expectStatus(await request(`/api/project-documents/${ids.documents.nativeLive}`,"member"),404);expectStatus(await deleteProjectDocument(env,actor("member"),ids.documents.nativeLive,NOW.toISOString()),204)});
  acceptanceCase(caseName("project-native.delete","creator.before.allowed"),async()=>{expectStatus(await deleteProjectDocument(env,actor("member"),ids.documents.nativeLive,NOW.toISOString()),204)});
  acceptanceCase(caseName("project-native.delete","creator.at.denied"),async()=>{await env.DB.prepare("UPDATE documents SET creator_deletion_until=? WHERE id=?").bind(AT,ids.documents.nativeLive).run();expectStatus(await deleteProjectDocument(env,actor("member"),ids.documents.nativeLive,NOW.toISOString()),403);expect(await env.DB.prepare("SELECT id FROM documents WHERE id=?").bind(ids.documents.nativeLive).first()).toBeTruthy()});
  acceptanceCase(caseName("project-native.delete","creator.after.denied"),async()=>{expectStatus(await deleteProjectDocument(env,actor("member"),ids.documents.nativeExpired,NOW.toISOString()),403)});
  it("uses the database execution clock in production even when the deadline changes after preflight",async()=>{let intercepted=false;const DB=new Proxy(env.DB,{get(target,property,receiver){if(property==="batch")return async(statements:D1PreparedStatement[])=>{intercepted=true;await env.DB.prepare("UPDATE documents SET creator_deletion_until=strftime('%Y-%m-%dT%H:%M:%fZ','now','-1 second') WHERE id=?").bind(ids.documents.nativeLive).run();return env.DB.batch(statements)};const value=Reflect.get(target,property,receiver);return typeof value==="function"?value.bind(target):value}});expectStatus(await deleteProjectDocument({...env,DB},actor("member"),ids.documents.nativeLive),403);expect(intercepted).toBe(true);expect(await env.DB.prepare("SELECT id FROM documents WHERE id=?").bind(ids.documents.nativeLive).first()).toBeTruthy()});
  acceptanceCase(caseName("project-native.provenance","deleted-creator.resolves-tombstone"),async()=>{const view=await request(`/api/projects/${ids.projects.active}`,"owner").then(r=>r.json<any>());expect(view.nativeDocuments.find((d:any)=>d.id===ids.documents.nativeDeletedCreator).creator_display_name).toBe("reference-deleted (former user)");expectStatus(await request(`/api/project-documents/${ids.documents.nativeDeletedCreator}`,"owner"),200)});
  acceptanceCase(caseName("project-native.provenance","deleted-revision-actor.resolves-tombstone"),async()=>{const history=await request(`/api/project-documents/${ids.documents.nativeDeletedCreator}/versions`,"owner").then(r=>r.json<any>());expect(history.versions[0]).toMatchObject({actor_id:ids.participants.deleted,actor_display_name:"reference-deleted (former user)"})});
  acceptanceCase(caseName("project-native.history","member.reads-revisions-and-metadata"),async()=>{const history=await request(`/api/project-documents/${ids.documents.nativeLive}/versions`,"member").then(r=>r.json<any>());expect(history.timeline).toEqual(expect.arrayContaining([expect.objectContaining({entry_type:"content_revision",version_number:1})]))});
  acceptanceCase(caseName("project-native.copy","new-id.independent"),async()=>{const response=await request(`/api/projects/${ids.projects.active}/native-documents/copy/${ids.documents.public}`,"owner",{method:"POST",headers:json,body:JSON.stringify({confirmProjectOwnership:true})});expectStatus(response,201);const copy=(await response.json<any>()).document;expect(copy.id).not.toBe(ids.documents.public);expect(copy).toMatchObject({owner:{type:"project",id:ids.projects.active},sourceDocumentId:ids.documents.public})});
  acceptanceCase(caseName("project-native.copy","source-deleted.copy-survives"),async()=>{const response=await request(`/api/projects/${ids.projects.active}/native-documents/copy/${ids.documents.public}`,"owner",{method:"POST",headers:json,body:JSON.stringify({confirmProjectOwnership:true})}),copy=(await response.json<any>()).document.id;expectStatus(await request(`/api/me/documents/${ids.documents.public}`,"owner",{method:"DELETE"}),204);expectStatus(await request(`/api/project-documents/${copy}`,"owner"),200)});
});

describe("reference world",()=>{
  it("contains stable aliases for the current semantic states",async()=>{expect((await env.DB.prepare("SELECT lifecycle_state FROM projects WHERE id=?").bind(ids.projects.archived).first<any>()).lifecycle_state).toBe("archived");expect((await env.DB.prepare("SELECT read_audience FROM projects WHERE id=?").bind(ids.projects.agentsOnly).first<any>()).read_audience).toBe("agents_only");expect((await env.DB.prepare("SELECT state FROM project_documents WHERE document_id IN (?,?) ORDER BY state").bind(ids.documents.suspendedContribution,ids.documents.retractedContribution).all()).results).toEqual([{state:"retracted"},{state:"suspended_after_removal"}]);expect((await env.DB.prepare("SELECT status,count(*) count FROM project_invitations GROUP BY status").all()).results).toEqual(expect.arrayContaining([expect.objectContaining({status:"outstanding"}),expect.objectContaining({status:"accepted"}),expect.objectContaining({status:"declined"}),expect.objectContaining({status:"revoked"})]))});
  it("keeps the project document when its creator account is finalized",async()=>{await env.DB.prepare("UPDATE participants SET account_state='deletion_pending',deletion_due_at=? WHERE id=?").bind("2029-01-01T00:00:00.000Z",ids.participants.member).run();await finalizeDueAccounts(env,NOW);expect(await env.DB.prepare("SELECT id FROM documents WHERE id=?").bind(ids.documents.nativeLive).first()).toBeTruthy()});
});

describe("acceptance inventory",()=>{
  it("makes every current branch and missing executable coverage searchable",()=>{const inventory=Object.entries(operationBranches).flatMap(([operation,branches])=>branches.map(branch=>caseName(operation as keyof typeof operationBranches,branch)));const report=inventory.map(name=>({name,covered:coveredCases.has(name)}));expect(report.filter(x=>x.covered).map(x=>x.name)).toEqual(expect.arrayContaining([...coveredCases]));expect(report.some(x=>!x.covered)).toBe(true)});
});
